# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9144be51fd44446629c452f2320226fb6d34999ed0bc4d45d5c331d580bba42ed253c4d6993707aebe96f303c54a3208620928e37ea847dfb5cf38fed9b087b5
  gcm_auth_key: AIzaSyA8iH9kaq_fPM-UHbV7UlW6HY8sDLMFJj8
  sms_ru_api_id:

test:
  secret_key_base: f8c429e4544fda8c6989babd7a0f0aabf9ea982f9462119ed6508822c9212eed9014c1c3c3c17dc912f921a98919e488751a6a51f9e70d88fb5f6d7f068ee7bb
  gcm_auth_key: AIzaSyA8iH9kaq_fPM-UHbV7UlW6HY8sDLMFJj8
  sms_ru_api_id:

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  gcm_auth_key: <%= ENV["GCM_AUTH_KEY"] %>
  sms_ru_api_id: <%= ENV["SMS_RU_API_ID"] %>
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
  aws_s3_bucket_name: <%= ENV["AWS_S3_BUCKET_NAME"] %>
